# Use Python 3.9 as the base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file into the container
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Python script and graph.json file into the container
COPY tp2.py .
COPY graph.json .

# Set the default command to run the Python script
CMD ["python", "tp2.py"]
